### ISSUE TITLE
Bug: Range Bar calculation is wrong

### ISSUE THREAD

**Issue by arminvandam1980** [afhacker/cAlgo.API.Extensions.Series#5]
Hi Ahmad,

I think the calculation of Range bar is wrong. The distance between High and Low must always be equal to the chosen BrickSize. So if you choose a RangeBar of 100 pips, the distance between High and Low of all bars should always be 100. That is not the case now.

Another issue is that the bars are not aligned with the calculation of the cTrader Rangebars. Maybe it's because of the above bug.

The RenkoBars is 100% correct and works perfectly.

Regards,
Armin

**Comment by amusleh-spotware-com** [comment]
Hi,
I will fix the Range bars, thanks for reporting
