### ISSUE TITLE
Rangebar is wrong

### ISSUE THREAD

**Issue by DaveAndersonCo** [afhacker/cAlgo.API.Extensions.Series#6]
I think the rangebar is wrong. I looked in the code and saw that the code is very different from the Renko. I always thought the range bar is identical to renko but only half of it. And there can also be gap between the bars, but in renko you have no gap. I tried to fix it, but couldn't.

Dave

**Comment by amusleh-spotware-com** [comment]
I'm aware of it, I will fix it whenever I got some free time.
